### ISSUE TITLE
Bad argument in libgui.lua on launch

### ISSUE THREAD

**Issue by kevin-kevjan** [ktaliaferro/gps-viewer#1]
after copy gpsViewer.lua and the gpsViewer directory to the /SCRIPTS/TOOLS directory and launching, I get error
"TOOLS/gpsViewer/libgui.lua:407 bad argument #2 to 'bor' (number"
dispalyed on TX16S TOOLS screen. 
RTN will clear error.

**Comment by ktaliaferro** [comment]
Hi Kevin, are you using an old version of EdgeTX?  It looks like VCENTER, the second argument to the bor function, was added in EdgeTX version 2.5. https://luadoc.edgetx.org/part_iii_-_opentx_lua_api_reference/constants/flags-and-pattern-constants

**Comment by kevin-kevjan** [comment]
Ugh.....you are 100% correct. (but worse)
I have multiple TX16 and in my excitment to get this loaded and try it out, I inadvertently grabbed my transmitter that has OPENTX (not even Edge) on it. 
Talk about User Error!!  
Issue resolved and closed, with my thanks
  👍
